"""create_qa_pairs_and_ingestion_runs

Revision ID: f2aa7b9accff
Revises: 
Create Date: 2026-04-22 13:47:14.022805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2aa7b9accff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_system_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('last_checkpoint', sa.Integer(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_pairs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_system_id', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('ingestion_method', sa.String(length=32), nullable=False),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_hash'),
    sa.UniqueConstraint('source_hash', name='uq_qa_pairs_source_hash')
    )
    with op.batch_alter_table('qa_pairs', schema=None) as batch_op:
        batch_op.create_index('idx_qa_pairs_captured_at', ['captured_at'], unique=False)
        batch_op.create_index('idx_qa_pairs_external_id', ['external_id'], unique=False)
        batch_op.create_index('idx_qa_pairs_source_system', ['source_system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa_pairs', schema=None) as batch_op:
        batch_op.drop_index('idx_qa_pairs_source_system')
        batch_op.drop_index('idx_qa_pairs_external_id')
        batch_op.drop_index('idx_qa_pairs_captured_at')

    op.drop_table('qa_pairs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
